service: aiseo-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  timeout: 29
  environment:
    NODE_ENV: production
    MONGODB_URI: ${env:MONGODB_URI, ''}
    MONGODB_DB_NAME: ${env:MONGODB_DB_NAME, ''}
    GOOGLE_APPLICATION_CREDENTIALS: ${env:GOOGLE_APPLICATION_CREDENTIALS, "./firebase-service-account.json"}

package:
  patterns:
    - "firebase-service-account.json"
    - "deepneurons-firebase-adminsdk-fbsvc-*.json"

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    exclude: [ "aws-sdk" ]
    target: "node20"

functions:
  trpc:
    handler: src/index.trpcHandler
    url:
      cors:
        allowedOrigins:
          - http://localhost:3000
          - https://aryan-dev.d9djpd2sux98b.amplifyapp.com
        allowedHeaders:
          - "*"
        allowedMethods:
          - "*"
        allowCredentials: true

  api:
    handler: src/index.openApiHandler
    url:
      cors:
        allowedOrigins:
          - http://localhost:3000
          - https://aryan-dev.d9djpd2sux98b.amplifyapp.com
        allowedHeaders:
          - "*"
        allowedMethods:
          - "*"
        allowCredentials: true
